import Link from "next/link";
import { ArrowUpRight,BookOpen } from "lucide-react";
import { requireUser } from "@/lib/auth";
import { db } from "@/lib/db";
import { Alert } from "@/components/Message";

export default async function InstructorHome({searchParams}:{searchParams:Promise<{error?:string;notice?:string}>}){
  const user=await requireUser("INSTRUCTOR"),p=await searchParams,now=new Date(),chartStart=new Date(now.getFullYear(),now.getMonth()-5,1);
  const [courses,enrollmentRows,sales,revenueStats,reviews,ratingStats,chartOrders]=await Promise.all([
    db.course.findMany({where:{instructorId:user.id},include:{_count:{select:{enrollments:true,reviews:true}}},orderBy:{updatedAt:"desc"}}),
    db.enrollment.findMany({where:{course:{instructorId:user.id}},select:{userId:true}}),
    db.order.findMany({where:{status:"COMPLETED",course:{instructorId:user.id}},include:{course:true,user:true},orderBy:{createdAt:"desc"},take:8}),
    db.order.aggregate({where:{status:"COMPLETED",course:{instructorId:user.id}},_sum:{amount:true},_count:{_all:true}}),
    db.review.findMany({where:{course:{instructorId:user.id}},include:{course:true,user:true},orderBy:{createdAt:"desc"},take:5}),
    db.review.aggregate({where:{course:{instructorId:user.id}},_avg:{rating:true}}),
    db.order.findMany({where:{status:"COMPLETED",createdAt:{gte:chartStart},course:{instructorId:user.id}},select:{amount:true,createdAt:true}}),
  ]);
  const revenue=revenueStats._sum.amount??0,avgOrder=revenueStats._count._all?revenue/revenueStats._count._all:0,uniqueStudents=new Set(enrollmentRows.map(r=>r.userId)).size;
  const series=Array.from({length:6},(_,index)=>{const month=new Date(now.getFullYear(),now.getMonth()-5+index,1),next=new Date(month.getFullYear(),month.getMonth()+1,1),amount=chartOrders.filter(o=>o.createdAt>=month&&o.createdAt<next).reduce((sum,o)=>sum+o.amount,0);return {label:month.toLocaleDateString("en-US",{month:"short"}),amount};}),maxSales=Math.max(1,...series.map(m=>m.amount)),popular=[...courses].sort((a,b)=>b._count.enrollments-a._count.enrollments).slice(0,4),maxStudents=Math.max(1,...popular.map(c=>c._count.enrollments));
  return <><div className="page-title-row"><div><div className="eyebrow">Your teaching studio</div><h1>Welcome, {user.firstName}.</h1><p>Here’s how your courses are finding their learners.</p></div><Link className="button button-small" href="/instructor/courses/new"><BookOpen size={14}/> Create course</Link></div><Alert error={p.error} success={p.notice}/><div className="stat-grid"><div className="stat-card"><small>Published courses</small><strong>{courses.filter(c=>c.status==="PUBLISHED").length}</strong><span className="stat-change">{courses.length} total courses</span></div><div className="stat-card"><small>Unique students</small><strong>{uniqueStudents}</strong><span className="stat-change">Across your courses</span></div><div className="stat-card"><small>Demo revenue</small><strong>${revenue.toLocaleString()}</strong><span className="stat-change">{revenueStats._count._all} completed orders</span></div><div className="stat-card"><small>Average rating</small><strong>{ratingStats._avg.rating?.toFixed(1)??"—"}</strong><span className="stat-change">${avgOrder.toFixed(0)} average order</span></div></div>
    <div className="split"><section className="panel"><div className="panel-header"><h2>Course performance</h2><Link href="/instructor/courses" className="text-link">Manage courses →</Link></div>{courses.length?courses.slice(0,5).map(c=><div key={c.id} className="course-row"><span className="category-symbol"><BookOpen size={16}/></span><div className="course-row-main"><strong>{c.title}</strong><small>{c._count.enrollments} learners · {c._count.reviews} reviews</small></div><span className={`pill ${c.status==="PUBLISHED"?"":"pill-gray"}`}>{c.status.toLowerCase()}</span><Link href={`/instructor/courses/${c.id}/edit`} className="text-link"><ArrowUpRight size={15}/></Link></div>):<div className="empty-state"><strong>Every great course starts somewhere</strong><Link href="/instructor/courses/new" className="text-link">Create your first course →</Link></div>}</section>
      <section className="panel"><div className="panel-header"><h2>Latest reviews</h2><Link href="/instructor/reviews" className="text-link">All reviews</Link></div>{reviews.length?reviews.map(r=><div key={r.id} className="course-row" style={{alignItems:"start"}}><span className="avatar-dot" style={{margin:0}}>{r.user.firstName[0]}{r.user.lastName[0]}</span><div className="course-row-main"><strong>{r.user.firstName} · {r.course.title}</strong><small style={{color:"#e29a41"}}>{"★".repeat(r.rating)}{"☆".repeat(5-r.rating)}</small><p className="small-note">{r.text}</p></div></div>):<div className="empty-state"><strong>No reviews yet</strong>Student feedback will show up here.</div>}</section></div>
    <div className="split" style={{marginTop:16}}><section className="panel"><div className="panel-header"><h2>Sales over time</h2><Link href="/instructor/sales" className="text-link">Sales report →</Link></div><div className="chart-bars">{series.map((m,i)=><div className="chart-column" key={m.label}><span className="chart-value">${m.amount}</span><div className="chart-bar" style={{height:`${Math.max(5,m.amount/maxSales*100)}%`,background:i%2?"#73cda2":"#8d95e8"}}/><small>{m.label}</small></div>)}</div></section><section className="panel"><div className="panel-header"><h2>Course popularity</h2><Link href="/instructor/students" className="text-link">Learners →</Link></div>{popular.length?popular.map(c=><div key={c.id} style={{marginBottom:13}}><div style={{display:"flex",justifyContent:"space-between",fontSize:11}}><span>{c.title}</span><strong>{c._count.enrollments}</strong></div><div className="progress-track"><span style={{width:`${c._count.enrollments/maxStudents*100}%`,background:"#9299e8"}}/></div></div>):<div className="empty-state"><strong>No courses yet</strong></div>}</section></div>
    <div className="panel" style={{marginTop:16}}><div className="panel-header"><h2>Recent sales</h2><Link href="/instructor/sales" className="text-link">All sales →</Link></div>{sales.length?<table className="data-table"><thead><tr><th>Student</th><th>Course</th><th>Date</th><th>Amount</th></tr></thead><tbody>{sales.slice(0,5).map(o=><tr key={o.id}><td>{o.user.firstName} {o.user.lastName}</td><td>{o.course.title}</td><td>{o.createdAt.toLocaleDateString()}</td><td>${o.amount}</td></tr>)}</tbody></table>:<div className="empty-state"><strong>Your sales will appear here</strong>Published courses help learners find you.</div>}</div>
  </>;
}
