import Link from "next/link";
import { notFound,redirect } from "next/navigation";
import { ArrowLeft,ArrowRight,CheckCircle2,LockKeyhole } from "lucide-react";
import { db } from "@/lib/db";
import { requireUser } from "@/lib/auth";
import { completeLesson } from "@/actions/learning";
import { youtubeEmbedUrl } from "@/lib/youtube";
import { TrackRecentCourse } from "@/components/TrackRecentCourse";
export default async function Player({params}:{params:Promise<{courseId:string;lessonId:string}>}){
 const {courseId,lessonId}=await params,user=await requireUser("STUDENT"),enrollment=await db.enrollment.findUnique({where:{userId_courseId:{userId:user.id,courseId}},include:{course:{include:{instructor:true,sections:{orderBy:{position:"asc"},include:{lessons:{orderBy:{position:"asc"}}}}}}}});if(!enrollment)notFound();const lessons=enrollment.course.sections.flatMap(s=>s.lessons),index=lessons.findIndex(l=>l.id===lessonId),lesson=lessons[index];if(!lesson)notFound();const progress=await db.lessonProgress.findMany({where:{userId:user.id,lessonId:{in:lessons.map(l=>l.id)},completed:true},select:{lessonId:true}}),done=new Set(progress.map(p=>p.lessonId)),percent=Math.round(done.size/lessons.length*100),next=lessons[index+1],previous=lessons[index-1];
 return <><TrackRecentCourse courseId={courseId} courseTitle={enrollment.course.title} /><div style={{maxWidth:1380,margin:"0 auto",padding:"24px 28px 50px"}}><Link className="text-link" href={`/student/courses/${courseId}/learn` }><ArrowLeft size={14} style={{display:"inline",verticalAlign:"-3px"}}/> Back to my courses</Link><div className="player-layout" style={{padding:0,marginTop:18}}><section><div className="video-frame">{lesson.videoUrl?<iframe src={youtubeEmbedUrl(lesson.videoUrl)} title={lesson.title} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen/>:<div style={{height:"100%",display:"grid",placeItems:"center",color:"white",textAlign:"center",padding:30}}><div><div style={{fontSize:44,marginBottom:12}}>✦</div><strong>{lesson.title}</strong><p style={{fontSize:12,color:"#b5c0d6"}}>This lesson is ready for your video link.</p></div></div>}</div><div className="page-title-row" style={{marginTop:20}}><div><div className="eyebrow">{enrollment.course.title}</div><h1 style={{fontSize:24}}>{lesson.title}</h1><p>{lesson.description}</p></div><span className="pill">{done.size} / {lessons.length} complete</span></div><div style={{display:"flex",justifyContent:"space-between",gap:8}}>{previous?<Link className="button button-outline button-small" href={`/student/courses/${courseId}/learn/${previous.id}`}><ArrowLeft size={14}/> Previous</Link>:<span/>}{done.has(lesson.id)?<span className="pill"><CheckCircle2 size={13} style={{display:"inline",verticalAlign:"-3px"}}/> Completed</span>:<form action={completeLesson}><input type="hidden" name="lessonId" value={lesson.id}/><button className="button button-small"><CheckCircle2 size={14}/> Mark as completed</button></form>}{next?<Link className="button button-quiet button-small" href={`/student/courses/${courseId}/learn/${next.id}`}>Next <ArrowRight size={14}/></Link>:null}</div></section><aside className="player-sidebar"><h3>Course content <span className="small-note">· {percent}% complete</span></h3><div className="progress-track" style={{margin:0,borderRadius:0,height:5}}><span style={{width:`${percent}%`}}/></div><div className="player-content">{enrollment.course.sections.map(section=><div key={section.id}><div className="curriculum-section"><strong style={{fontSize:11}}>{section.title}</strong></div>{section.lessons.map((l,i)=><Link key={l.id} href={`/student/courses/${courseId}/learn/${l.id}`} className="lesson-line" style={{background:l.id===lesson.id?"#f1f2ff":"var(--paper)",color:l.id===lesson.id?"var(--brand)":"var(--ink)"}}><span>{done.has(l.id)?<CheckCircle2 size={14} style={{display:"inline",verticalAlign:"-2px",marginRight:6,color:"#58b987"}}/>:<span className="small-note" style={{marginRight:8}}>{i+1}.</span>}{l.title}</span>{done.has(l.id)?null:<LockKeyhole size={12} color="#98a2b3"/>}</Link>)}</div>)}</div></aside></div></div></>;
}
