export type CourseBadge = "NEW" | "BESTSELLER" | null;

export const catalogContent = [
  { slug: "design-systems", category: "Programming", categorySlug: "programming", title: "Python for Data Analysis with Pandas", subtitle: "Turn raw datasets into clear answers with a practical Python workflow.", description: "Clean real-world data, explore patterns with pandas, build visual summaries, and package a repeatable analysis workflow from notebooks to reusable scripts.", price: 69, originalPrice: 119, level: "INTERMEDIATE", instructor: ["Nadia", "Rahman"], rating: 4.8, reviews: 632, learners: 18500, lessons: 12, durationMinutes: 195, badge: "BESTSELLER", cover: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1000&q=85" },
  { slug: "modern-react", category: "Web Development", categorySlug: "web-development", title: "React Query Deep Dive: Caching and Server State", subtitle: "Build responsive React apps with dependable data fetching.", description: "Master query keys, caching, mutations, optimistic updates, pagination, and error handling by building a data-rich React interface step by step.", price: 74, originalPrice: 129, level: "ADVANCED", instructor: ["Marcus", "Bennett"], rating: 4.9, reviews: 418, learners: 12400, lessons: 11, durationMinutes: 222, badge: "BESTSELLER", cover: "https://images.unsplash.com/photo-1579403124614-197f69d8187b?auto=format&fit=crop&w=1000&q=85" },
  { slug: "visual-machine-learning", category: "DevOps", categorySlug: "devops", title: "Production Machine Learning with Docker", subtitle: "Package, test, and ship repeatable machine-learning services.", description: "Containerize a small inference API, manage model artifacts, add health checks, and prepare a reproducible deployment pipeline for production-minded teams.", price: 82, originalPrice: null, level: "ADVANCED", instructor: ["Elena", "Petrova"], rating: 4.7, reviews: 286, learners: 8300, lessons: 9, durationMinutes: 248, badge: "NEW", cover: "https://images.unsplash.com/photo-1531297484001-80022131f5a1?auto=format&fit=crop&w=1000&q=85" },
  { slug: "founder-playbook", category: "Programming", categorySlug: "programming", title: "FastAPI: Design and Build Production APIs", subtitle: "Create typed, documented APIs with a clean Python architecture.", description: "Design request and response models, validate data, organize routers, connect a database, and write practical tests for a maintainable FastAPI service.", price: 59, originalPrice: null, level: "INTERMEDIATE", instructor: ["Ibrahim", "Khan"], rating: 4.8, reviews: 355, learners: 9100, lessons: 10, durationMinutes: 216, badge: "NEW", cover: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1000&q=85" },
  { slug: "practical-security", category: "DevOps", categorySlug: "devops", title: "Terraform for Cloud Infrastructure", subtitle: "Provision consistent environments with reusable infrastructure code.", description: "Model cloud resources, use variables and modules, manage state safely, and build a reviewable infrastructure workflow that supports repeatable deployments.", price: 79, originalPrice: 139, level: "ADVANCED", instructor: ["Sofia", "Martinez"], rating: 4.9, reviews: 512, learners: 14600, lessons: 12, durationMinutes: 265, badge: "BESTSELLER", cover: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1000&q=85" },
  { slug: "prompt-engineering", category: "DevOps", categorySlug: "devops", title: "GitHub Actions: CI/CD from First Workflow to Release", subtitle: "Automate testing and delivery with practical GitHub workflows.", description: "Create reliable build and test jobs, use workflow artifacts and secrets safely, add deployment gates, and publish a release from a real repository.", price: 64, originalPrice: null, level: "INTERMEDIATE", instructor: ["Daniel", "Okafor"], rating: 4.7, reviews: 201, learners: 5100, lessons: 8, durationMinutes: 174, badge: "NEW", cover: "https://images.unsplash.com/flagged/photo-1579274216947-86eaa4b00475?auto=format&fit=crop&w=1000&q=85" },
  { slug: "python-beyond-basics", category: "Programming", categorySlug: "programming", title: "Python Automation for Everyday Work", subtitle: "Replace repetitive tasks with small, dependable Python tools.", description: "Work with files, spreadsheets, APIs, and scheduled jobs while learning how to structure scripts, handle errors, and make useful automation safe to run.", price: 55, originalPrice: null, level: "BEGINNER", instructor: ["Grace", "Kim"], rating: 4.6, reviews: 189, learners: 6100, lessons: 9, durationMinutes: 185, badge: "NEW", cover: "https://images.unsplash.com/photo-1587620962725-abab7fe55159?auto=format&fit=crop&w=1000&q=85" },
  { slug: "cloud-architecture", category: "DevOps", categorySlug: "devops", title: "Kubernetes Workloads and Production Deployments", subtitle: "Move from containers to resilient orchestrated applications.", description: "Deploy workloads, configure services and probes, manage secrets and resource limits, and diagnose common cluster issues with a realistic application.", price: 89, originalPrice: null, level: "ADVANCED", instructor: ["Omar", "Haddad"], rating: 4.8, reviews: 441, learners: 12200, lessons: 13, durationMinutes: 292, badge: "BESTSELLER", cover: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1000&q=85" },
  { slug: "content-strategy", category: "Web Development", categorySlug: "web-development", title: "Responsive Web Design with Modern CSS", subtitle: "Create flexible layouts that feel polished on every screen.", description: "Use fluid type, grid, flexbox, container queries, and accessible interaction patterns to turn a static design into a responsive, production-ready website.", price: 49, originalPrice: null, level: "BEGINNER", instructor: ["Aisha", "Cole"], rating: 4.7, reviews: 315, learners: 7800, lessons: 10, durationMinutes: 169, badge: null, cover: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=1000&q=85" },
  { slug: "polished-css", category: "Web Development", categorySlug: "web-development", title: "CSS Architecture and Design Systems", subtitle: "Build a visual language that stays consistent as products grow.", description: "Create reusable tokens and components, organize styles at scale, handle themes, and document a design system that keeps a multi-page interface cohesive.", price: 69, originalPrice: 119, level: "ADVANCED", instructor: ["Theo", "Williams"], rating: 4.9, reviews: 803, learners: 24100, lessons: 13, durationMinutes: 234, badge: "BESTSELLER", cover: "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=1000&q=85" },
  { slug: "javascript-essentials", category: "Programming", categorySlug: "programming", title: "Modern JavaScript: Async, Modules, and Testing", subtitle: "Write modular JavaScript that is easier to understand and trust.", description: "Practice modern syntax, asynchronous control flow, module boundaries, browser APIs, and focused tests by improving a small interactive application.", price: 62, originalPrice: null, level: "INTERMEDIATE", instructor: ["Lena", "Fischer"], rating: 4.8, reviews: 510, learners: 19900, lessons: 12, durationMinutes: 250, badge: null, cover: "https://images.unsplash.com/photo-1675495666589-94cdafbcfcc8?auto=format&fit=crop&w=1000&q=85" },
  { slug: "sql-everyday-analysis", category: "Programming", categorySlug: "programming", title: "SQL Query Optimization and Data Modeling", subtitle: "Make relational queries clearer, faster, and easier to maintain.", description: "Model useful tables, read query plans, choose indexes, avoid common performance traps, and work through reporting queries against a realistic dataset.", price: 54, originalPrice: null, level: "INTERMEDIATE", instructor: ["Ravi", "Shah"], rating: 4.7, reviews: 372, learners: 9600, lessons: 10, durationMinutes: 206, badge: null, cover: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1000&q=85" },
  { slug: "html-css-first-website", category: "Web Development", categorySlug: "web-development", title: "Next.js Storefront: From Pages to Checkout", subtitle: "Build a polished storefront with routing and reusable product UI.", description: "Create an accessible product catalog, responsive detail pages, reusable layouts, and a convincing checkout flow using modern full-stack web patterns.", price: 79, originalPrice: null, level: "INTERMEDIATE", instructor: ["Mina", "Youssef"], rating: 4.8, reviews: 690, learners: 22500, lessons: 14, durationMinutes: 262, badge: "BESTSELLER", cover: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1000&q=85" },
  { slug: "ui-design-figma", category: "Mobile App Development", categorySlug: "mobile-development", title: "React Native Apps Ready for Release", subtitle: "Design, build, and prepare a cross-platform app for real devices.", description: "Build native-feeling screens, connect navigation and forms, handle loading states, and prepare a React Native project for device testing and release.", price: 64, originalPrice: 119, level: "INTERMEDIATE", instructor: ["Ethan", "Brooks"], rating: 4.6, reviews: 220, learners: 7500, lessons: 11, durationMinutes: 227, badge: "NEW", cover: "https://images.unsplash.com/photo-1551650975-87deedd944c3?auto=format&fit=crop&w=1000&q=85" },
  { slug: "react-native-mobile-apps", category: "Mobile App Development", categorySlug: "mobile-development", title: "Expo and React Native: Ship Your First App", subtitle: "Take an idea from development build to a tested mobile release.", description: "Set up Expo, build reusable screens, persist app data, test on-device behavior, and learn the steps that turn a prototype into a shareable application.", price: 72, originalPrice: null, level: "BEGINNER", instructor: ["Zara", "Ali"], rating: 4.8, reviews: 288, learners: 8600, lessons: 10, durationMinutes: 238, badge: "NEW", cover: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=1000&q=85" },
  { slug: "csharp-programming-fundamentals", category: "Programming", categorySlug: "programming", title: "C# and .NET: Build Maintainable Services", subtitle: "Move from language fundamentals to a clean service architecture.", description: "Use modern C#, dependency injection, configuration, validation, and tests to build a small .NET service with clear boundaries and practical error handling.", price: 67, originalPrice: null, level: "INTERMEDIATE", instructor: ["Noah", "Campbell"], rating: 4.9, reviews: 374, learners: 10200, lessons: 12, durationMinutes: 276, badge: null, cover: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1000&q=85" },
  { slug: "docker-devops-foundations", category: "DevOps", categorySlug: "devops", title: "Docker to Kubernetes: Deploy a Real Service", subtitle: "Containerize an app and take it through a practical deployment.", description: "Write a multi-stage image, configure local services, add health checks, and deploy the same application to a Kubernetes environment with a repeatable workflow.", price: 79, originalPrice: null, level: "INTERMEDIATE", instructor: ["Amara", "Johnson"], rating: 4.7, reviews: 534, learners: 16300, lessons: 12, durationMinutes: 254, badge: "BESTSELLER", cover: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=1000&q=85" },
  { slug: "git-github-workflow", category: "Programming", categorySlug: "programming", title: "Git Branching and GitHub Collaboration", subtitle: "Make team changes easier to review, merge, and release.", description: "Practice a clean branching strategy, resolve conflicts, write useful pull requests, review code, and keep a shared repository healthy as a team.", price: 48, originalPrice: null, level: "BEGINNER", instructor: ["Lucas", "Fernandez"], rating: 4.6, reviews: 1240, learners: 50300, lessons: 9, durationMinutes: 154, badge: null, cover: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1000&q=85" },
  { slug: "nextjs-web-apps", category: "Web Development", categorySlug: "web-development", title: "Next.js App Router: Build a Full-Stack Product", subtitle: "Connect layouts, server rendering, and data mutations in one app.", description: "Build a complete product experience with nested routes, server components, form actions, persistent data, and thoughtful loading and error states.", price: 84, originalPrice: null, level: "ADVANCED", instructor: ["Priya", "Desai"], rating: 4.9, reviews: 815, learners: 28700, lessons: 14, durationMinutes: 284, badge: "BESTSELLER", cover: "https://images.unsplash.com/photo-1551033406-611cf9a28f67?auto=format&fit=crop&w=1000&q=85" },
  { slug: "practical-typescript", category: "Programming", categorySlug: "programming", title: "TypeScript at Scale: Generics and Design Patterns", subtitle: "Model complex application behavior without losing clarity.", description: "Design expressive types, use generics and discriminated unions, improve API boundaries, and refactor a growing codebase while keeping the developer experience clear.", price: 74, originalPrice: null, level: "ADVANCED", instructor: ["Maya", "Chen"], rating: 4.8, reviews: 954, learners: 32000, lessons: 15, durationMinutes: 305, badge: null, cover: "https://images.unsplash.com/photo-1624996752380-8ec242e0f85d?auto=format&fit=crop&w=1000&q=85" },
] as const;

export function getCatalogContent(slug: string) {
  return catalogContent.find((course) => course.slug === slug) ?? null;
}

export function getCourseBadge(slug: string): CourseBadge {
  return getCatalogContent(slug)?.badge ?? null;
}
