import { mkdir,writeFile,unlink } from "node:fs/promises";
import path from "node:path";
import { randomUUID } from "node:crypto";
import { NextResponse } from "next/server";
import { getUser } from "@/lib/auth";
import { db } from "@/lib/db";

export const runtime="nodejs";
const extensions:Record<string,string>={"image/jpeg":"jpg","image/png":"png","image/webp":"webp","image/gif":"gif"};
function validImage(bytes:Buffer,type:string){if(type==="image/jpeg")return bytes[0]===0xff&&bytes[1]===0xd8&&bytes[2]===0xff;if(type==="image/png")return bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10]));if(type==="image/gif")return bytes.subarray(0,3).toString()==="GIF";if(type==="image/webp")return bytes.subarray(0,4).toString()==="RIFF"&&bytes.subarray(8,12).toString()==="WEBP";return false;}
export async function POST(request:Request){const user=await getUser();if(!user)return NextResponse.json({error:"Sign in to update your profile photo"},{status:401});const form=await request.formData(),file=form.get("avatar");if(!(file instanceof File)||file.size===0||file.size>2*1024*1024||!extensions[file.type])return NextResponse.json({error:"Choose an image under 2 MB"},{status:400});const bytes=Buffer.from(await file.arrayBuffer());if(!validImage(bytes,file.type))return NextResponse.json({error:"This image file could not be verified"},{status:400});const publicRoot=path.resolve(process.cwd(),"public"),uploadDir=path.resolve(process.cwd(),process.env.UPLOAD_DIR??"public/uploads");if(!uploadDir.startsWith(publicRoot+path.sep))return NextResponse.json({error:"Upload directory must be inside public"},{status:500});await mkdir(uploadDir,{recursive:true});const filename=`${randomUUID()}.${extensions[file.type]}`,target=path.join(uploadDir,filename),url=`/${path.relative(publicRoot,target).replaceAll("\\","/")}`;await writeFile(target,bytes,{flag:"wx"});await db.profile.upsert({where:{userId:user.id},create:{userId:user.id,avatarUrl:url},update:{avatarUrl:url}});return NextResponse.json({url});}
export async function DELETE(){const user=await getUser();if(!user)return NextResponse.json({error:"Unauthorized"},{status:401});const profile=await db.profile.findUnique({where:{userId:user.id}});if(profile?.avatarUrl?.startsWith("/")){const publicRoot=path.resolve(process.cwd(),"public"),target=path.resolve(publicRoot,`.${profile.avatarUrl}`);if(target.startsWith(publicRoot+path.sep))await unlink(target).catch(()=>{});}await db.profile.upsert({where:{userId:user.id},create:{userId:user.id},update:{avatarUrl:null}});return NextResponse.json({ok:true});}
